### ISSUE TITLE
NullPointerException at resetPasswordWithToken

### ISSUE THREAD

**Issue by hal-matts** [googlesamples/android-testdpc#103]
1. Set device PIN '0000'
2. Create work profile.
-- on work profile --
3. Get new token.
4. Reset profile passwod '1234'
 then

2020-03-18 18:54:00.913 20310-20310/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afwsamples.testdpc, PID: 20310
    java.lang.NullPointerException: Attempt to get length of null array
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.resetPasswordWithToken(IDevicePolicyManager.java:10070)
        at android.app.admin.DevicePolicyManager.resetPasswordWithToken(DevicePolicyManager.java:3172)
        at com.afwsamples.testdpc.policy.resetpassword.ResetPasswordWithTokenFragment.resetPasswordWithToken(ResetPasswordWithTokenFragment.java:235)
        at com.afwsamples.testdpc.policy.resetpassword.ResetPasswordWithTokenFragment.onClick(ResetPasswordWithTokenFragment.java:165)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.RemoteException: Remote stack trace:
        at java.security.MessageDigest.update(MessageDigest.java:372)
        at com.android.server.locksettings.SyntheticPasswordCrypto.personalisedHash(SyntheticPasswordCrypto.java:202)
        at com.android.server.locksettings.SyntheticPasswordManager.transformUnderSecdiscardable(SyntheticPasswordManager.java:1054)
        at com.android.server.locksettings.SyntheticPasswordManager.unwrapTokenBasedSyntheticPassword(SyntheticPasswordManager.java:920)
        at com.android.server.locksettings.LockSettingsService.setLockCredentialWithTokenInternal(LockSettingsService.java:2669)

**Comment by thevery** [comment]
You should check `isResetPasswordTokenActive` before calling `resetPasswordWithToken`.

**Comment by ghankit** [comment]
I am too facing the same issue but in a different scenario. 

1. Lock the device using DPM 
2. Reboot the device
3. Once device is rebooted try to unlock the device with the token created while locking the device. 
4. `resetPasswordWithToken()` throws `java.lang.NullPointerException: Attempt to get length of null array`

The same thing works fine if the device is not rebooted, i.e.  the token is getting deactivated/invalidated by the system after reboot. 

Note : Using push notification to trigger lock and unlock functions

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
