### ISSUE TITLE
Application crash on low end devices

### ISSUE THREAD

**Issue by abhisheksubal** [googlesamples/android-testdpc#127]
autoGrantRequestedPermissionToSelf() causing problems on Low end devices.

main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x71a0b948 self=0x7271ae2000
  | sysTid=26841 nice=0 cgrp=default sched=0/0 handle=0x7273052ee8
  | state=S schedstat=( 92984272 62356919 177 ) utm=5 stm=4 core=7 HZ=100
  | stack=0x7ff2d2e000-0x7ff2d30000 stackSize=8192KB
  | held mutexes=
  at sun.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1723)
  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3446)
  at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1752)
  at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)
  at android.app.admin.DevicePolicyManager.setPermissionGrantState(DevicePolicyManager.java:10583)
  at com.afwsamples.testdpc.provision.PostProvisioningTask.autoGrantRequestedPermissionsToSelf(PostProvisioningTask.java:186)
  at com.afwsamples.testdpc.provision.PostProvisioningTask.performPostProvisioningOperations(PostProvisioningTask.java:86)
  at com.afwsamples.testdpc.provision.ProvisioningSuccessActivity.onCreate(ProvisioningSuccessActivity.java:39)
  at android.app.Activity.performCreate(Activity.java:7963)
  at android.app.Activity.performCreate(Activity.java:7952)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:237)
  at android.app.ActivityThread.main(ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by jscott1989** [comment]
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.
