### ISSUE TITLE
SideLoading android-testdpc not working

### ISSUE THREAD

**Issue by guanhuay** [googlesamples/android-testdpc#14]
Hi, just found a wierd bug today. Here is what happen:

i try to side load this testdpc to my android device using Android Studio. I am sure i have all the pre-req dependency installed. Then when i try to configure the testDPC to on my android devices.
If i click on SET UP and wait for the work profile to be create. But the problem is after i click on SET UP, it supposed to prompt to ask me do i wish to add a account or skip to the AFW. However, i never seen such prompt. It either show no further respond or pop up a "Unfortunatly, testDPC has stopped" warning. Such that the work profile cannot be created.

I also try to install the testDPC from Google Play Store, for that app, it work and the work profile is configure just as expected.

Any idea what i do wrong or is there any problem with the app?

Thanks for your guys help.

**Comment by ming030890** [comment]
A bugreport right after issue would be very helpful.

**Comment by guanhuay** [comment]
@ming030890 Hi here is the bugreport file.
[bugreport.zip](https://github.com/googlesamples/android-testdpc/files/507351/bugreport.zip)

**Comment by ming030890** [comment]
TestDPC crashes, sound same issue of https://github.com/googlesamples/android-testdpc/issues/9

 Bad process com.afwsamples.testdpc uid 1010124: crashed at time 171245
      Short msg: java.lang.ClassNotFoundException
      Long msg: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.afwsamples.testdpc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.afwsamples.testdpc-2/lib/arm64, /vendor/lib64, /system/lib64]]
      Stack:
        java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.afwsamples.testdpc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.afwsamples.testdpc-2/lib/arm64, /vendor/lib64, /system/lib64]]
        	at android.app.ActivityThread.installProvider(ActivityThread.java:5162)
        	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4754)
        	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4694)
        	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        	at android.os.Handler.dispatchMessage(Handler.java:102)
        	at android.os.Looper.loop(Looper.java:148)
        	at android.app.ActivityThread.main(ActivityThread.java:5423)
        	at java.lang.reflect.Method.invoke(Native Method)
        	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.afwsamples.testdpc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.afwsamples.testdpc-2/lib/arm64, /vendor/lib64, /system/lib64]]
        	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        	at android.app.ActivityThread.installProvider(ActivityThread.java:5147)
        	... 10 more
        	Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.FileProvider
        		at java.lang.Class.classForName(Native Method)
        		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 12 more
        	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by guanhuay** [comment]
@ming030890 I just get the github version of testdpc working by doing a factory reset and re-sideload the testdpc into my device, now it worked.

Thanks for your help @ming030890 :)
