### ISSUE TITLE
how to set password token active?

### ISSUE THREAD

**Issue by lijheng** [googlesamples/android-testdpc#149]
The 'activeToken' button is always disabeld in "ResetPasswordWithTokenFragment" page. And  I click "NewToken" will trigger an exception such as: 
```
Process: com.afwsamples.testdpc, PID: 24695
    java.lang.SecurityException: Escrow token is disabled on the current user
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setResetPasswordToken(IDevicePolicyManager.java:14675)
        at android.app.admin.DevicePolicyManager.setResetPasswordToken(DevicePolicyManager.java:4913)
        at com.afwsamples.testdpc.policy.resetpassword.ResetPasswordWithTokenFragment.createNewPasswordToken(ResetPasswordWithTokenFragment.java:189)
        at com.afwsamples.testdpc.policy.resetpassword.ResetPasswordWithTokenFragment.onClick(ResetPasswordWithTokenFragment.java:157)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.locksettings.LockSettingsService.addEscrowToken(LockSettingsService.java:3264)
        at com.android.server.locksettings.LockSettingsService.access$1300(LockSettingsService.java:188)
        at com.android.server.locksettings.LockSettingsService$LocalService.addEscrowToken(LockSettingsService.java:3646)
        at com.android.internal.widget.LockPatternUtils.addEscrowToken(LockPatternUtils.java:1353)
        at com.android.server.devicepolicy.DevicePolicyManagerService.lambda$setResetPasswordToken$115$DevicePolicyManagerService(DevicePolicyManagerService.java:15326)
```
Please tell me what can I do, Please.

**Comment by lijheng** [comment]
My device mode is Pixel 4a, Android 12.

**Comment by lijheng** [comment]
ok

**Comment by vishalguptahmh** [comment]
have you find any solution for this?

**Comment by lijheng** [comment]
> have you find any solution for this? i have used `adb shell dpm set-device-owner <packagename>/<DAdminreceiver>` to put my in device owner mode.
> 
> app status is also showing its in device owner mode. but things are not working as expected.
> 
> <img alt="Screenshot 2022-07-01 at 5 19 46 PM" width="438" src="https://user-images.githubusercontent.com/8852510/176889039-187a785a-4ece-4745-8dde-5640bf94837e.png">

Sorry for the late reply. Firstly you need reset your device to factory settings, and you should't set device password anyway  before call  `setResetPasswordToken` .
