### ISSUE TITLE
Unable to setup managed profile

### ISSUE THREAD

**Issue by micaelpn** [googlesamples/android-testdpc#212]
Hi,

I am unable to setup a managed profile. I get the error "Can't set up profile" when starting the provisioning process. Steps to reproduce : 

1. Install Test DPC app
2. Open Set up Test DPC app
3. Select Set up managed profile and click next without changing "Select provisioning parameters"
4. Click on "accept & continue" on the following screen
5. Error "Can't set up profile" with a toast "Provisioning failed or cancelled"

I followed the instructions shared [on the documentation](https://source.android.com/docs/devices/admin/testing-setup) : after reseting my device, I tried to issue the command `adb shell dpm set-device-owner com.afwsamples.testdpc/.DeviceAdminReceiver` but I received the following error : 

```
com.afwsamples.testdpc/.DeviceAdminReceiver was already an admin for user 0. No need to set it again.

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:10737)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:9394)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:264)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:87)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11170)
	at android.os.Binder.shellCommand(Binder.java:1226)
	at android.os.Binder.onTransact(Binder.java:1039)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6330)
	at android.os.Binder.execTransactInternal(Binder.java:1501)
	at android.os.Binder.execTransact(Binder.java:1440)
```

I also see the following warning from adb logcat command : 

```
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: Bad device admin requested for user=35: ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver}
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: org.xmlpull.v1.XmlPullParserException: headless-system-user mode must be valid
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at android.app.admin.DeviceAdminInfo.<init>(DeviceAdminInfo.java:377)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at com.android.server.devicepolicy.DevicePolicyManagerService.findAdmin(DevicePolicyManagerService.java:3214)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at com.android.server.devicepolicy.DevicePolicyManagerService.setActiveAdmin(DevicePolicyManagerService.java:3741)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at com.android.server.devicepolicy.DevicePolicyManagerService.enableAndSetActiveAdmin(DevicePolicyManagerService.java:21061)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at com.android.server.devicepolicy.DevicePolicyManagerService.enableAdminAndSetProfileOwner(DevicePolicyManagerService.java:21053)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at com.android.server.devicepolicy.DevicePolicyManagerService.createAndProvisionManagedProfile(DevicePolicyManagerService.java:20788)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6007)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at android.os.Binder.execTransactInternal(Binder.java:1496)
05-01 01:29:57.660  1484  3994 W DevicePolicyManager: 	at android.os.Binder.execTransact(Binder.java:1440)
...
05-01 01:29:58.592  1484  4421 D DevicePolicyManager: checkProvisioningPreCondition(android.app.action.PROVISION_MANAGED_DEVICE, com.afwsamples.testdpc) failed: Cannot set the device owner if the device is already set-up.
```

Here is the device information : 

- Test DPC version : 9.0.8
- Device : Pixel 8
- Android version : 14
- Build number : AP1A.240405.002

Any idea ?

Thank you

**Comment by GrapeJelly** [comment]
I am having the same problem with ADB. Everything was working fine until today when TestDPC started displaying "This app is not an admin" and Set Up TestDPC now displays "TestDPC isn't currently allowed to be set up as the profile or device owner."

Test DPC version : 9.0.8
Device : Pixel 8 Pro
Android version : 14

**Comment by micaelpn** [comment]
I received the update v9.0.9. I confirm that it works again.

Thank you for your quick fix !

**Comment by pfmaggi** [comment]
TestDPC v9.0.9 is now at 100% roll-out on the Play store including a fix for this issue. I'll update the repository on github as soon as possible.
