### ISSUE TITLE
Exception while testing generateKeyPair

### ISSUE THREAD

**Issue by AISoldierWYN** [googlesamples/android-testdpc#215]
Exception while testing generateKeyPair

Here is some produce and error info. Sames like some wrong in org.bouncycastle. But I have no idea to fix it. Generate key pair is ok but occurs exception while analyzing it.

STEPS TO REPRODUCE: (please be specific)
1.click menu "Generate a private/public key pair"
2.selcet "Make user-selcetable", "Inclue key attestation challenge" and "Inclue device serial number"
3.click ok

REPRODUCE RATE:
5 times out of 5 tries

Error stack:
05-30 20:47:23.322 11164 11164 E PolicyManagement: Failed parsing attestation record, Exception:
05-30 20:47:23.322 11164 11164 E PolicyManagement: java.lang.IllegalStateException: unexpected object: org.bouncycastle.asn1.DLSet
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at org.bouncycastle.asn1.ASN1UniversalType.checkedCast(Unknown Source:38)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at org.bouncycastle.asn1.ASN1TaggedObject.getBaseUniversal(Unknown Source:16)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at org.bouncycastle.asn1.ASN1TaggedObject.getBaseUniversal(Unknown Source:6)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.afwsamples.testdpc.policy.utils.AuthorizationList.<init>(AuthorizationList.java:219)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.afwsamples.testdpc.policy.utils.Attestation.<init>(Attestation.java:80)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.afwsamples.testdpc.policy.keymanagement.GenerateKeyAndCertificateTask.showKeyGenerationResult(GenerateKeyAndCertificateTask.java:192)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.afwsamples.testdpc.policy.keymanagement.GenerateKeyAndCertificateTask.onPostExecute(GenerateKeyAndCertificateTask.java:159)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.afwsamples.testdpc.policy.keymanagement.GenerateKeyAndCertificateTask.onPostExecute(GenerateKeyAndCertificateTask.java:51)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.Looper.loopOnce(Looper.java:205)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.os.Looper.loop(Looper.java:294)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-30 20:47:23.322 11164 11164 E PolicyManagement: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Device: Pixel 5
OS Version: android 14
Test dpc version 9.0.6

**Comment by CamsShaft** [comment]
I've been getting something similar and it causes the testdpc app to crash. I was assuming it had something to do with the challenge base64 but even without it selected it still does it... too bad, I wanted to see what the pair looked like
