### ISSUE TITLE
TestDPC crash when rotation on CreateWiFiConfiguration

### ISSUE THREAD

**Issue by sungm1n** [googlesamples/android-testdpc#62]
It can be reproduced with TestDPC 4.0.6. Please check the below crash log.

05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime: FATAL EXCEPTION: main
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime: Process: com.afwsamples.testdpc, PID: 22112
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.FragmentTransaction android.app.FragmentManager.beginTransaction()' on a null object reference
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.app.DialogFragment.dismissInternal(DialogFragment.java:297)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.app.DialogFragment.dismiss(DialogFragment.java:268)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at com.afwsamples.testdpc.policy.wifimanagement.WifiConfigCreationDialog.onDismiss(WifiConfigCreationDialog.java:152)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1433)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:164)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:6687)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-23 11:28:37.980 1410280 22112 22112 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
05-23 11:28:37.987  1000  3570  3591 I zygote64: Wrote stack traces to '[tombstoned]'
05-23 11:28:37.990  1000  3587  3600 I zygote64: Thread[3,tid=3600,WaitingInMainSignalCatcherLoop,Thread*=0x7ecd6c9400,peer=0x12d40220,"Signal Catcher"]: reacting to signal 3
05-23 11:28:37.990  1000  3587  3600 I zygote64: 
05-23 11:28:37.991  1000  2061  3708 W ActivityManager:   Force finishing activity com.afwsamples.testdpc/.PolicyManagementActivity

**Comment by macarthor** [comment]
i think this app should not consider so much as a demo

**Comment by lynnye** [comment]
This is already fixed in TestDPC 5.0.0 and after.
