### ISSUE TITLE
Get android.os.strictmode.DiskWriteViolation exception while start action.ACTION_PROVISION_MANAGED_PROFILE

### ISSUE THREAD

**Issue by demonguy** [googlesamples/android-testdpc#81]
I tried to write my own sample like this
`                Intent intent = new Intent(DevicePolicyManager.ACTION_PROVISION_MANAGED_PROFILE);
                intent.putExtra(DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME, new ComponentName(getApplicationContext(), AdminReceiver.class));
//                intent.putExtra("android.app.extra.PROVISIONING_SKIP_USER_CONSENT", true);
                startActivityForResult(intent, 1);`

However , i got 

> 02-26 23:51:47.632  4006  4006 D StrictMode: StrictMode policy violation; ~duration=27 ms: android.os.strictmode.DiskWriteViolation
02-26 23:51:47.632  4006  4006 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1460)
02-26 23:51:47.632  4006  4006 D StrictMode: 	at libcore.io.BlockGuardOs.mkdir(BlockGuardOs.java:196)
02-26 23:51:47.632  4006  4006 D StrictMode: 	at android.system.Os.mkdir(Os.java:323)
02-26 23:51:47.632  4006  4006 D StrictMode: 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:608)

In logcat. I have no idea why this happen. I didn't enable strictmode in my application

**Comment by demonguy** [comment]
#

- 

1.
